### ISSUE TITLE
Better Campfires prevents server start on Linux fabric server

### ISSUE THREAD

**Issue by bdragon28** [CaoTrongThang/better-campfires-1.20.1#6]
Due to the Utils class borrowing a logger from an internal class that does not exist on all server platforms, Better Campfires does not work on Linux dedicated servers currently.

See

https://github.com/CaoTrongThang/better-campfires-1.20.1/blob/fbaeb9db34824f9c6a5e1de00986e08493cc54b8/src/main/java/com/trongthang/bettercampfires/Utils.java#L14

```
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 2024-12-27 16:01:10
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: com/mojang/text2speech/Narrator
	at knot//com.trongthang.bettercampfires.DataHandler.loadCampfiresData(DataHandler.java:42)
	at knot//com.trongthang.bettercampfires.DataHandler.initializeCampfiresData(DataHandler.java:37)
	at knot//com.trongthang.bettercampfires.BetterCampfires.lambda$onInitialize$0(BetterCampfires.java:48)
	at knot//net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:38)
	at knot//net.minecraft.server.MinecraftServer.handler$ccj000$fabric-lifecycle-events-v1$beforeSetupServer(MinecraftServer.java:5337)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: com.mojang.text2speech.Narrator
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 8 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.10.2-x86_64-linode165
	Java Version: 17.0.13, Debian
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Debian
	Memory: 1282225664 bytes (1222 MiB) / 3019898880 bytes (2880 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7542 32-Core Processor
	Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 10035.78
	Virtual memory used (MB): 5741.07
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512M -Xmx6G
	Fabric Mods: 
		airhop: Air Hop 8.0.2
		all_the_fan_made_discs: All The Fan Made Discs 0.5.6
		alloy_forgery: Alloy Forgery 2.1.2+1.20
		amethystgravity: Amethyst Gravity: Reattracted 2.0.0+1.20.1
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		armorful: Armorful 3.1.3+1.20.1
		attributefix: AttributeFix 21.0.4
		azurelib: AzureLib 2.0.41
		azurelibarmor: AzureLib Armor 2.0.14
		backported_wolves: Backported Wolves 1.1.0-1.19.3-1.20.4
		balm-fabric: Balm 7.3.10
			kuma_api: KumaAPI 20.1.9-SNAPSHOT
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		betterarcheology: Better Archeology 1.2.1-1.20.1
		betterbiomeblend: Better Biome ReBlend 1.4.2
		bettercampfires: Better Campfires 2.4
		bettercombat: Better Combat 1.8.6+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.4
		betterend: Better End 4.0.11
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.6
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betternether: Better Nether 9.0.10
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		blahaj: Blåhaj 0.3.2
		blockrunner: Block Runner 8.0.4
		blocky_bass: Blocky Bass 1.0.18
		bookshelf: Bookshelf 20.2.13
		botarium: Botarium 2.3.4
			team_reborn_energy: Energy 3.0.0
		bountiful: Bountiful 6.0.4+1.20.1
		brutes_dropscraps_mr: Brutes Drop Scraps 1.1
		burnt: Burnt Basic Fabric 1.6.0
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		carryon: Carry On 2.1.2.7
		casualness_delight: Casualness Delight Fabric 1.20.1-0.4-FDR
		chunky: Chunky 1.3.146
		cicada: CICADA 0.9.1+1.20.1
		clay: Clay Soldiers 1.0.0
		cloth-config: Cloth Config v11 11.1.136
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.4
		collective: Collective 7.87
		companion: Companion 5.2.2+fabric
		corgilib: CorgiLib 4.0.3.3
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		coroutil: CoroUtil 1.20.1-1.3.7
		cratedelight: Crate Delight 24.11.22-1.20-fabric
		create: Create 0.5.1-j-build.1631+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.8+1.20.1
			porting_lib_base: Porting Lib Base 2.3.8+1.20.1
				porting_lib_gui_utils: Porting Lib Gui Utils 2.3.8+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.8+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.8+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.8+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.8+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.8+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.8+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.8+1.20.1
				porting_lib_common: Porting Lib Common 2.3.8+1.20.1
			porting_lib_models: Porting Lib Models 2.3.8+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.8+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.8+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.8+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.8+1.20.1
				porting_lib_core: Porting Lib Core 2.3.8+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.8+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.8+1.20.1
			registrate-fabric: Registrate for Fabric 1.3.79-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create_structures: Create: Structures 1.1.0
		create_ultimate_factory: Create: Ultimate Factory 1.8.0
		creeperoverhaul: Creeper Overhaul 3.0.2
		crittersandcompanions: Critters and Companions 2.2.2
		culinaryconstruct: Culinary Construct 5.2.1+1.20.1
		culturaldelights: Cultural Delights Fabric 1.0.5+1.20.1
			mm: Manningham Mills 2.3
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		cupboard: cupboard 1.20.1-2.7
		cursery: Cursery Mod 1.20.1-4.1
		darkwaters: Dark Waters 0.0.22
		dawn: Dawn API 5.0.0
			terraform-shapes-api-v1: Terraform Shapes API (v1) 7.0.1
		deeperdarker: Deeper and Darker 1.3.2.1
			customportalapi: Custom Portal Api 0.0.1-beta64-1.20
		delightfulcreators: Delightful Creators 1.3-1.20.x-FDR-support
		dimdoors: DimensionalDoors 5.4.1
			com_flowpowered_flow-math: flow-math 1.0.3
			com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
			org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		distantfriends: Distant Friends 0.5.5
		do_a_barrel_roll: Do a Barrel Roll 3.6.1+1.20.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		doggomodoverhauled: Doggo Mod Overhauled 5.3.1
		dungeonnowloading: Dungeon Now Loading 1.5
		dungeons_arise: When Dungeons Arise 2.1.57
		dynamiccrosshair: Dynamic Crosshair 9.3
			dynamiccrosshair-api: DynamicCrosshair API 1.1
		dynamiccrosshaircompat: Dynamic Crosshair Compat 4.0
		easyanvils: Easy Anvils 8.0.2
		easymagic: Easy Magic 8.0.1
		easyshulkerboxes: Easy Shulker Boxes 8.0.2
			puzzlesapi: Puzzles Api 8.1.6
				puzzlesaccessapi: Puzzles Access Api 8.0.9
		elytra_recipe: Elytra recipe 1.0.0
		elytraslot: Elytra Slot 6.4.4+1.20.1
			mixinsquared: MixinSquared 0.1.2-beta.6
		elytratime: Elytra Time 2.0.0
		elytratrims: Elytra Trims 3.5.4
			conditional-mixin: conditional mixin 0.6.2
		emi: EMI 1.1.18+1.20.1+fabric
		endersdelight: Ender's Delight Refabricated 1.20.1-1.0.2.refabricated
		entityculling: EntityCulling 1.7.2
		estrogen: Create: Estrogen 4.3.1+1.20.1-fabric
			baubly: Baubly 1.0.1
			com_teamresourceful_resourceful-cosmetics-4j: resourceful-cosmetics-4j 1.0.4
			critter_lib: Critter Library 0.1-beta.11
			jukeboxfix: Jukeboxfix 1.0.0+1.20.1
		exposure: Exposure 1.7.7
		extra-enchantments-and-curses: Extra Enchantments and Curses 1.8.1
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.13.0+kotlin.2.1.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.1.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.26.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		farmersdelight: Farmer's Delight 1.20.1-2.2.4+refabricated
			porting_lib_config: Porting Lib Config 2.3.8+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.8+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.8+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.8+1.20.1
		fastmove: FastMove - Parkour Movement 1.0.8
		featurerecycler: Feature Recycler 1.0.0
		ferritecore: FerriteCore 6.0.1
		festive_delight: Festive Delight 1.0.0
		flowermimics: Flower Mimics 2.0
		forgeconfigapiport: Forge Config API Port 8.0.1
		framework: Framework 0.6.16
			org_javassist_javassist: javassist 3.29.2-GA
		friendsandfoes: Friends & Foes 3.0.6
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		frightsdelight: Fright's Delight 1.2.2
		frozenlib: FrozenLib 1.9.3-mc1.20.1
		geckolib: GeckoLib 4 4.4.9
			com_eliotlash_mclib_mclib: mclib 20
		geode_plus: Geode Plus 1.2.5
		gigeresque: Gigeresque 0.5.72
			bettercrawling: Better Crawling 1.0.101
		gravity_changer_q: Gravity Changer (qouteall fork) 1.1.2
		guardvillagers: GuardVillagers 2.0.9-1.20.1
		hardcorerevival: Hardcore Revival 12.0.6
		heartstone: Heartstone 1.20-1.3.0
		hexcasting: Hex Casting 0.11.2
			serialization_hooks: Serialization Hooks 0.4.99999
		illwalls: Illusory Walls 0.2.0+1.20
			kibu-hook-api: Kibu Hook API 1.2.0
			kibu-hooks: Kibu Hooks 0.12.0+1.20
			kibu-nbt-api: Kibu NBT API 0.5.0
			kibu-schematic-api: Kibu Schematic API 0.8.0
			kibu-schematic-fabric: Kibu Schematic API Fabric 0.2.0+1.20
		immersive_melodies: Immersive Melodies 0.3.0+1.20.1
		immersive_weathering: Immersive Weathering 1.20.1-2.0.3
		immersiveui: ImmersiveUI 0.2.2
		inline: Inline 1.20.1-1.0.2
		inventory_tabs: Inventory Tabs 1.4.0+1.20
		inventorytotem: Inventory Totem 3.3
		jade: Jade 11.12.0+fabric
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.20.0.105
		jewelry: Jewelry (RPG Series) 1.3.7+1.20.1
		kambrik: Kambrik 6.1.1+1.20.1
		keep-inventory-penalty: Keep Inventory Penalty 2.0.1
		kiwi: Kiwi Library 11.8.28+fabric
		leavesbegone: Leaves Be Gone 8.0.0
		lexiconfig: Lexiconfig 1.3.11
		lithium: Lithium 0.11.2
		lootr: Lootr 0.7.35.85
		map_atlases: Map Atlases 2.6.0
		maple_delight: Maple Delight 0.2.1
		maxhealthfix: MaxHealthFix 12.0.3
		memoryleakfix: Memory Leak Fix 1.1.5
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		mobs_attempt_parkour: Mobs Attempt Parkour 0.5.2-1.20
			maelstrom_library: Maelstrom Library 1.6.1-1.20
		moonlight: Moonlight 1.20-2.13.40
		more_armor_trims: More Armor Trims 1.4.1-1.20.1
		moredelight: More Delight 24.9.27-1.20-fabric
		mr_no_moreglowlichen: No More Glow Lichen 1.0.1
		mr_player_headdrop: Player Head Drop 1.0
		mr_tidal_towns: Tidal Towns 1.3.4
		mru: Mineblock's Repeated Utilities 1.0.4+1.20.1+fabric
		muffins_thaidelight: Muffin's Thai's Delight 1.0.0
		mythicmetals: Mythic Metals 0.19.9+1.20.1
			additionalentityattributes: Additional Entity Attributes 1.7.3+1.20.0
			common-protection-api: Common Protection API 1.0.0
		naturallychargedcreepers: Naturally Charged Creepers 3.5
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		necronomicon: Necronomicon 1.6.0
		nethermap: Better Nether Map 3.0.0-1.20.1
		netherportalfix: NetherPortalFix 13.0.1
		nethersdelight: Nether's Delight Refabricated 1.20.1-4.1.1
		noanimaltemptdelay: No Animal Tempt Delay 1.2
		notenoughanimations: NotEnoughAnimations 1.8.2
		nyctophobia: Nyctophobia 1.9
			omega-config: OmegaConfig 1.2.2-1.18.1
		nyfsspiders: Nyf's Spiders 2.1.1
		oceansdelight: Ocean's Delight fdrf-fabric-1.0.2-1.20
		octolib: OctoLib 0.4.2
		overworldanchor: Temmie's Overworld Anchor 1.0.1
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		paucal: PAUCAL 0.6.0+1.20.1-fabric
		pebbles_partyapi: Pebble's Party API 1.0.0
		philipsruins: Philip`s Ruins 1.20.1
		player-animator: Player Animator 1.0.2-rc1+1.20
		polymorph: Polymorph 0.49.8+1.20.1
			spectrelib: SpectreLib 0.13.17+1.20.1
		portablehole: Portable Hole 8.0.0
		potionparticlepack: potionparticlepack 1.0.1
		puzzleslib: Puzzles Lib 8.1.25
		ranged_weapon_api: RangedWeaponAPI 1.1.4+1.20.1
		resourcefulconfig: Resourcefulconfig 2.1.2
		resourcefullib: Resourceful Lib 2.1.29
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		respawnablepets: Respawnable Pets 1.20-1
		rpgdifficulty: RpgDifficulty 1.3.16
		rusticdelight: Rustic Delight 1.0.1
		scout: Scout 2.0.4+1.20.1
			lib39-core: Lib39 (Core) 1.5.0-experimental6.1+1.20.1
			lib39-dessicant: Lib39 (Dessicant) 1.5.0-experimental6.1+1.20.1
		shield_api: Shield API 1.0.1+1.20.1
		showmeyourskin: Show Me Your Skin! 1.9.0+1.20
		simplemod: SimpleMod 1.20.1
		simpleradio: SimpleRadio 2.4.6.1
			polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.19+1.20.1
		simplyswords: Simply Swords 1.56.0-1.20.1
		sliceanddice: Create Slice & Dice 3.3.1
		smartbrainlib: SmartBrainLib 1.15
		smwyg: Show Me What You Got 1.1.1
		sn0wfrogs_capybaras: Sn0wfrog's Capybaras 1.1.0-mc1.20.1
		sneakycurses: Sneaky Curses 8.0.2
		snowrealmagic: Snow! Real Magic! 10.5.4
		solid_mobs: Solid Mobs 1.7.1
		sortilege: Sortilege 1.6.1
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.4.8
		sparsestructures: SparseStructures 2.2.0
		spawnproof-villagers: Spawn-Proof Villagers 1.0.0+1.19.4
		spell_power: Spell Power Attribute 0.12.0+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		spiceoffabric: Spice of Fabric 1.6.2+mc1.20.1
			capsaicin: Capsaicin 1.3.3+mc1.20.1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
		stoneworks: Stoneworks 8.0.0
		storagedelight: Storage Delight 24.12.15-1.20-fabric
		storagedrawers: Storage Drawers 12.10.5
		structure_pool_api: Structure Pool API 1.0+1.20.1
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		surveyor: Surveyor Map Framework 0.6.24+1.20
			folk_sisby_kaleido-config: kaleido-config 0.3.1+1.3.2
		surveyor_atlases: Surveyor Atlases 0.1.0
		sustenance: Sustenance 1.1.2
			org_yaml_snakeyaml: snakeyaml 2.2
		swampier_swamps: Swampier Swamps 1.20-4.0.0
		teamgui: Crim's Party GUI 1.0.0
		tectonic: Tectonic 2.4.1b
		terrablender: TerraBlender 3.0.1.7
		terrainslabs: Countered's Terrain Slabs 1.3.0
		the_bumblezone: The Bumblezone - Fabric 7.5.7+1.20.1-fabric
			athena: Athena 3.1.1
		thiccpackets: Extra Thicc Packets 1.17-1.19+
		tintedflowers: Biome Tinted Flowers 1.0.5
		tradingpost: Trading Post 8.0.2
		trinkets: Trinkets 3.7.2
		ubesdelight: Ube's Delight 0.2.3
			porting_lib_registries: Porting Lib Registries 2.3.4+1.20.1
		universal_ores: Universal Ores 1.5.2
		vegandelight: Vegan Delight 1.1.0
		vietnamsdelight: Vietnam's Delight 1.0.2-1.20.1
		villagernames: Villager Names 8.1
		visualworkbench: Visual Workbench 8.0.0
		voicechat: Simple Voice Chat 1.20.1-2.5.27
		wandering_collector: Wandering Collector 1.2.1+mc1.20-pre5
		waterdripsound: Drip Sounds 1.19-0.3.2
		watut: What Are They Up To 1.20.1-1.1.3
		wetlands: Beneath the Wetlands 1.2
		wilderwild: Wilder Wild 3.0.7-mc1.20.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.2+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.12.0
			com_twelvemonkeys_common_common-io: common-io 3.12.0
			com_twelvemonkeys_common_common-lang: common-lang 3.12.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.12.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.12.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.12.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.6
		yungscavebiomes: YUNG's Cave Biomes 1.20.1-Fabric-2.0.0
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
	Server Running: true
	Data Packs: vanilla, fabric, dimdoors:classic (incompatible), dimdoors:default (incompatible), gigeresque:friendsandfoescompat, gigeresque:betterendcompat, Immersive Weathering Generated Pack, tectonic/tectonic
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by CaoTrongThang** [comment]
I removed it in the latest version, see if it's fixed

**Comment by CaoTrongThang** [comment]
closed for no activities
